[tool.poetry]
name = "hitster"
version = "0.1.0"
description = ""
authors = ["fjlein <fjlein@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typst = "^0.13.0"
spotipy = "^2.25.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
